// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $about from "./routes/about.tsx";
import * as $image_slug_ from "./routes/image/[slug].ts";
import * as $index from "./routes/index.tsx";
import * as $HalfCut from "./islands/HalfCut.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $Shrooms from "./islands/Shrooms.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/about.tsx": $about,
    "./routes/image/[slug].ts": $image_slug_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/HalfCut.tsx": $HalfCut,
    "./islands/Hero.tsx": $Hero,
    "./islands/Shrooms.tsx": $Shrooms,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
